### ISSUE TITLE
Talk: How to read template error messages

### ISSUE THREAD

**Issue by dermojo** [cpp-aachen/cpp-aachen.github.io#10]
**Title:** How to read template error messages

**Length:** about 1 hour

**Status:** Concept phase

**Required preparation time:** ~3-4 weeks

**Description:**
When templates go "wrong" in C++, the compiler errors are very long, hard to understand and quickly scare away people.
My idea for this talk is to take ~3 common cases for template error (e.g. missing << when printing, missing < when sorting, nested templates with a missing member/function deep down) and go through the error messages created by GCC, Clang and MSVC.
We'll identify how these messages are structured, so that we can identify a way to quickly navigate them.
Also, I'll probably find some tools to shorten them / make them more readable.

**Comment by d-frey** [comment]
Scheduled for 2024-04-10
