### ISSUE TITLE
Talk: CMake File Sets and Self Contained Headers

### ISSUE THREAD

**Issue by johnfranklinrickard** [cpp-aachen/cpp-aachen.github.io#17]
Title: CMake File Sets and self contained header tests

Length: ~30 minutes

Status: concept 

Required preparation time: ~1-2 weeks

Description:
This talk presents ways to test your public headers and CMake targets for correctness. This can be done with the (relatively) new features of self contained header verification tests through CMake directly. Will also describe CMake File Sets (as prerequisite).

**Comment by d-frey** [comment]
@johnfranklinrickard Can we schedule this talk for 2024-04-10

**Comment by d-frey** [comment]
Scheduled for 2024-04-10
