### ISSUE TITLE
Talk: WTF-8

### ISSUE THREAD

**Issue by daixtrose** [cpp-aachen/cpp-aachen.github.io#23]

**Comment by d-frey** [comment]
Title: WTF-8
Duration: 10-15 minutes
Author: Daniel Frey
Preparation: 1-2 weeks
Synopsis: The WTF-8 standard and why you should care about it.

**Comment by d-frey** [comment]
OK, it was *slightly* longer than 15 minutes 😇

Done on 2024-06-05
