### ISSUE TITLE
Allow to submit talk suggestions as issues.

### ISSUE THREAD

**Issue by dermojo** [cpp-aachen/cpp-aachen.github.io#9]
Hey!

As discussed, I think it's a good idea to submit ideas/suggestions for lightning or longer talks as GitHub issues. I'll start :)

It would be helpful if there was a template, indicating not only title, but also (expected) length and necessary preparation time.
I'll open a few issues with my suggestions and will try to find a suitable format.

**Comment by johnfranklinrickard** [comment]
I like the general Idea and template.
Additional suggestion: Instead of starting each title with Talk Suggestion, one could introduce a label for these issues.

**Comment by SvenJo** [comment]
Done. New presentation are reviewed in the preparation meeting
